// <auto-generated />
using System;
using BDRD.DemoCICD.CRUDAPP.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDApp.Web.Database.TodoMigrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("BDRD.DemoCICD.CRUDAPP.Web.Application.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("todo_item_id");

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("todo_item_due_date")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("todo_item_name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("todo_item_note");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("todo_item_start_date")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("todo_item_status");

                    b.HasKey("Id")
                        .HasName("tbl_todo_item_pk");

                    b.ToTable("tbl_todo_item", (string)null);
                });

            modelBuilder.Entity("BDRD.DemoCICD.CRUDAPP.Web.Application.Models.TodoItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("todo_item_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("todo_item_status_name");

                    b.HasKey("Id")
                        .HasName("tbl_todo_item_status_pk");

                    b.ToTable("tbl_todo_item_status", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
